- src/app/login/page.js
> added login page UI

- src/Components/AboutUs/AboutBanner.js
Added the About Us page banner.
> Added the About Us page banner

- src/app/aboutus/page.js
Added the About Us page layout.
> Added the About Us page layout

- package-lock.json
- package.json
- src/app/aboutus/page.js
> Added Banefits section

- src/Components/FoundersQuotes.js
- src/app/aboutus/page.js
Added the FoundersQuotes section.
> Added the FoundersQuotes section

- src/Components/OurStory.js
- src/app/aboutus/page.js
> Added OurStory section

- src/app/page.js
- src/components/Home/Stats/Stats.jsx
- src/components/Shared/Navbar/Navbar.jsx
- src/components/Shared/Navbar/Navlinks/Navlinks.jsx
Added stats in home page and updata navbar minor desing.
> Added stats in home page and updata navbar minor desing

- next.config.js
- src/components/BookDetails/BookDetails.jsx
- src/components/BookDetails/Related/Related.jsx
Redesing book details page Related section.
> Redesing book details page Related section

- src/components/AddBook/AddBook.jsx
> Update add book page UI

- src/components/BookDetails/BookDetails.jsx
> Upade book details page UI

- src/components/AboutUs/OurStories/OurStory.jsx
- src/components/AboutUs/Teams/Teams.jsx
- src/components/BookDetails/BookDetails.jsx
- src/components/BuyAllBooks/BuyAllBooks.jsx
- src/components/Contact/Contact.jsx
- src/components/Shared/Navbar/Navend/Navend.jsx
Upadate about us page and contact us page UI.
> Upadate about us page and contact us page UI

- src/components/UserDashboard/Message/Message.jsx
> Update message ui

- src/app/dashboard/add-banner/page.js
- src/components/UserDashboard/AddBanner/AddBanner.jsx
- src/components/UserDashboard/Dashboard.jsx
Added add banner page in dashboard.
> Added add banner page in dashboard

- src/components/UserDashboard/AddBanner/AddBanner.jsx
Make add banner page responsive.
> Make add banner page responsive

- src/app/globals.css
- src/components/UserDashboard/Message/Message.jsx
> update chat info ui

- src/components/UserDashboard/AddBanner/AddBanner.jsx
> update add banner page.

- src/Hooks/api/useSpecificUserBook.jsx
- src/components/UserDashboard/AddBanner/AddBanner.jsx
- src/components/UserDashboard/AddBlog/AddBlog.jsx
- src/components/UserDashboard/MyBooks/MyBooks.jsx
- src/components/UserDashboard/users/Users.jsx
> Update mybook page UI

- src/app/dashboard/exchange-books/page.js
- src/app/dashboard/list-exchange/page.js
- src/components/UserDashboard/ExchangeBook/ExchangeBook.jsx
- src/components/UserDashboard/MyBooks/MyBooks.jsx
> Update exchange book page UI.

- src/app/dashboard/track-order/page.js
- src/components/UserDashboard/Dashboard.jsx
Added order track page in dashboard.
> Added order track page in dashboard.

- src/components/Shared/Navbar/Navbar.jsx
- src/components/UserDashboard/AddBanner/AddBanner.jsx
- src/components/joinUs/JoinUs.jsx
Fix nav menu hamburger not show in small screen.
> Fix nav menu hamburger not show in small screen.
